def run_command cmd
  puts "--> executing: #{cmd}"
  puts "--> Remember to commit the resulting specs to the Porta repo."
  system cmd
end

# The file name depends on the 'namespace' defined in the Listener.
def spec_file(type)
  res = 'docs/active_docs/Service Management API'
  res << ' (on-premises)' if type == :on_prem
  "#{res}.json"
end

def generate_docs(type)
  spec = spec_file(type)
  cmd = type == :saas ? 'SAAS_SWAGGER=1' : 'SAAS_SWAGGER=0'
  cmd << ' bundle exec source2swagger -f lib/3scale/backend/listener.rb -c "##~" -o docs/active_docs/.'
  run_command cmd
  # source2swagger is really bad at generating readable JSON
  require 'json'
  File.write(spec, JSON.pretty_generate(JSON.parse(File.read(spec))) << "\n")
end

namespace :docs do
  namespace :swagger do
    namespace :generate do
      # The swagger specs generated by these tasks need to be committed to the
      # Porta repo: https://github.com/3scale/porta/tree/master/doc/active_docs
      # (Service Management API (on-premises).json and Service Management
      # API.json)

      desc "Generates all swagger docs"
      task all: [:saas, :on_prem]

      desc "Generates swagger docs for SaaS"
      task :saas do
        generate_docs(:saas)
      end

      desc "Generates swagger docs for on-prem"
      task :on_prem do
        generate_docs(:on_prem)
      end
    end
  end
end
