# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{3scale_backend}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Cigánek"]
  s.date = %q{2010-05-17}
  s.description = %q{This gem provides a daemon that handles authorization and reporting of web services managed by 3scale.}
  s.email = %q{adam@3scale.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "3scale_backend.ru",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "configuration.rb",
     "data/postfile",
     "data/postfile1",
     "data/postfile18",
     "data/postfile3",
     "lib/3scale/backend.rb",
     "lib/3scale/backend/action.rb",
     "lib/3scale/backend/actions/authorize.rb",
     "lib/3scale/backend/actions/check.rb",
     "lib/3scale/backend/actions/report.rb",
     "lib/3scale/backend/aggregation.rb",
     "lib/3scale/backend/aggregation/configuration.rb",
     "lib/3scale/backend/aggregation/rule.rb",
     "lib/3scale/backend/application.rb",
     "lib/3scale/backend/archiver.rb",
     "lib/3scale/backend/archiver/s3_storage.rb",
     "lib/3scale/backend/configuration.rb",
     "lib/3scale/backend/contract.rb",
     "lib/3scale/backend/errors.rb",
     "lib/3scale/backend/metric.rb",
     "lib/3scale/backend/metric/collection.rb",
     "lib/3scale/backend/numeric_hash.rb",
     "lib/3scale/backend/route.rb",
     "lib/3scale/backend/service.rb",
     "lib/3scale/backend/storable.rb",
     "lib/3scale/backend/storage.rb",
     "lib/3scale/backend/storage_key_helpers.rb",
     "lib/3scale/backend/time_hacks.rb",
     "lib/3scale/backend/transactor.rb",
     "lib/3scale/backend/transactor/status.rb",
     "lib/3scale/backend/usage_limit.rb",
     "lib/rack/fiber_pool.rb",
     "script/benchmark",
     "script/console",
     "test/integration/application_test.rb",
     "test/integration/authorize_test.rb",
     "test/integration/check_test.rb",
     "test/integration/report_test.rb",
     "test/test_helper.rb",
     "test/test_helpers/assert_change.rb",
     "test/test_helpers/event_machine.rb",
     "test/test_helpers/integration.rb",
     "test/test_helpers/master_service.rb",
     "test/test_helpers/sequences.rb",
     "test/test_helpers/storage_keys.rb",
     "test/unit/action_test.rb",
     "test/unit/aggregation/rule_test.rb",
     "test/unit/aggregation_test.rb",
     "test/unit/archiver/s3_storage_test.rb",
     "test/unit/archiver_test.rb",
     "test/unit/contract_test.rb",
     "test/unit/errors_test.rb",
     "test/unit/metric/collection_test.rb",
     "test/unit/metric_test.rb",
     "test/unit/numeric_hash_test.rb",
     "test/unit/route_test.rb",
     "test/unit/service_test.rb",
     "test/unit/storage_key_helpers_test.rb",
     "test/unit/storage_test.rb",
     "test/unit/time_hacks_test.rb",
     "test/unit/transactor/status_test.rb",
     "test/unit/transactor_test.rb",
     "test/unit/usage_limit_test.rb"
  ]
  s.homepage = %q{http://www.3scale.net}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{3scale web service management system backend}
  s.test_files = [
    "test/integration/report_test.rb",
     "test/integration/check_test.rb",
     "test/integration/authorize_test.rb",
     "test/integration/application_test.rb",
     "test/unit/transactor/status_test.rb",
     "test/unit/archiver/s3_storage_test.rb",
     "test/unit/storage_test.rb",
     "test/unit/usage_limit_test.rb",
     "test/unit/metric_test.rb",
     "test/unit/service_test.rb",
     "test/unit/archiver_test.rb",
     "test/unit/time_hacks_test.rb",
     "test/unit/aggregation/rule_test.rb",
     "test/unit/transactor_test.rb",
     "test/unit/storage_key_helpers_test.rb",
     "test/unit/errors_test.rb",
     "test/unit/numeric_hash_test.rb",
     "test/unit/metric/collection_test.rb",
     "test/unit/route_test.rb",
     "test/unit/contract_test.rb",
     "test/unit/aggregation_test.rb",
     "test/unit/action_test.rb",
     "test/test_helpers/event_machine.rb",
     "test/test_helpers/storage_keys.rb",
     "test/test_helpers/master_service.rb",
     "test/test_helpers/sequences.rb",
     "test/test_helpers/assert_change.rb",
     "test/test_helpers/integration.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-s3>, ["~> 0.6"])
      s.add_runtime_dependency(%q<builder>, ["~> 2.1"])
      s.add_runtime_dependency(%q<eventmachine>, ["~> 0.12"])
      s.add_runtime_dependency(%q<em-redis>, ["~> 0.2"])
      s.add_runtime_dependency(%q<hoptoad_notifier>, ["~> 2.2"])
    else
      s.add_dependency(%q<aws-s3>, ["~> 0.6"])
      s.add_dependency(%q<builder>, ["~> 2.1"])
      s.add_dependency(%q<eventmachine>, ["~> 0.12"])
      s.add_dependency(%q<em-redis>, ["~> 0.2"])
      s.add_dependency(%q<hoptoad_notifier>, ["~> 2.2"])
    end
  else
    s.add_dependency(%q<aws-s3>, ["~> 0.6"])
    s.add_dependency(%q<builder>, ["~> 2.1"])
    s.add_dependency(%q<eventmachine>, ["~> 0.12"])
    s.add_dependency(%q<em-redis>, ["~> 0.2"])
    s.add_dependency(%q<hoptoad_notifier>, ["~> 2.2"])
  end
end

