production:
  main:
    # TODO: replace with the real one.
    master_provider_key: "master"

  archiver:
    path: "/tmp/transactions"
    s3_bucket: "s3_bucket"

  aws: &AWS
    access_key_id:     "aws_access_key_id2"
    secret_access_key: "secret_access_key"

  redis:
    db: 0


development:
  main:
    master_provider_key: "master"

  archiver:
    path: "/tmp/transactions"
    s3_bucket: "s3_bucket"
  
  aws: *AWS

  redis:
    db: 1


test:
  main:
    master_provider_key: "master"

  archiver:
    path: "/tmp/transactions"

  aws:
    access_key_id: invalid
    secret_access_key: invalid
  
  redis:
    db: 2
