#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f $0)")
. ${SCRIPT_DIR}/lib/functions

case $1 in
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    *)
        echo Please specify either start or stop as parameter. >&2
        exit 1
esac

