#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f $0)")
. ${SCRIPT_DIR}/lib/functions

export RACK_ENV=test

start_services

bundle exec rake
EXITVAL=$?

if [ -z "$CI" ]; then
    stop_services
fi

exit ${EXITVAL}
