#!/bin/bash

function do_license_check()
{
    if [ -n "$CI" ]; then
        bundle exec rake license_finder
    fi
}

function do_test()
{
    case $1 in
    sync)
        echo "==================== Running tests using the SYNC Redis driver ===================="
        CONFIG_REDIS_ASYNC=false bundle exec rake
        ;;
    async)
        echo "==================== Running tests using the ASYNC Redis driver ===================="
        CONFIG_REDIS_ASYNC=true bundle exec rake
        ;;
    *)
      echo "Invalid Redis driver option: $1"
      exit 1
    esac
}

function run_tests()
{
    export RACK_ENV=test

    do_license_check && do_test "sync" && do_test "async"
}

if ! run_tests; then
    echo "Tests failed" >&2
    exit 1
fi
