#!/usr/bin/env ruby

reschedule_jobs_freq = ENV['RESCHEDULE_JOBS_FREQ'] || 300
loop do
  system('rake', '--trace=stdout', 'reschedule_failed_jobs') or raise 'task crashed'
  ENV['ONCE'] ? exit : sleep(reschedule_jobs_freq)
end
