version: '3'
services:
  redis-master:
    image: redis:6.2-alpine
    container_name: redis-master
    network_mode: host
    volumes:
      - ./run:/var/run/redis:z
    command: [ redis-server, --port, "6379", --unixsocket, "/var/run/redis/redis.sock", --unixsocketperm, "777" ]

  redis-replica1:
    image: redis:6.2-alpine
    container_name: redis-replica1
    network_mode: host
    command: [ redis-server, --slaveof, localhost, "6379", --port, "6380" ]

  redis-replica2:
    image: redis:6.2-alpine
    container_name: redis-replica2
    network_mode: host
    command: [ redis-server, --slaveof, localhost, "6379", --port, "6381" ]

  redis-sentinel1:
    image: redis:6.2-alpine
    container_name: redis-sentinel1
    network_mode: host
    volumes:
      - ./sentinel1:/data:Z
    command: [ redis-server, /data/sentinel1.conf, --sentinel, --port, "26379" ]

  redis-sentinel2:
    image: redis:6.2-alpine
    container_name: redis-sentinel2
    network_mode: host
    volumes:
      - ./sentinel2:/data:Z
    command: [ redis-server, /data/sentinel2.conf, --sentinel, --port, "26380" ]

  redis-sentinel3:
    image: redis:6.2-alpine
    container_name: redis-sentinel3
    network_mode: host
    volumes:
      - ./sentinel3:/data:Z
    command: [ redis-server, /data/sentinel3.conf, --sentinel, --port, "26381" ]

  tls-redis-master:
    image: redis:6.2-alpine
    container_name: tls-redis-master
    network_mode: host
    volumes:
      - ./run:/var/run/redis:z
      - ./master.conf:/etc/redis.conf:z
      - ./circleci.crt:/etc/redis.crt:z
      - ./circleci.key:/etc/redis.key:z
      - ./ca-circleci-cert.pem:/etc/ca-root-cert.pem:z
    command: [ redis-server, /etc/redis.conf ]

  tls-redis-replica1:
    image: redis:6.2-alpine
    container_name: tls-redis-replica1
    network_mode: host
    volumes:
      - ./replica1.conf:/etc/redis.conf:z
      - ./circleci.crt:/etc/redis.crt:z
      - ./circleci.key:/etc/redis.key:z
      - ./ca-circleci-cert.pem:/etc/ca-root-cert.pem:z
    command: [ redis-server, /etc/redis.conf, --slaveof, localhost, "46380" ]

  tls-redis-replica2:
    image: redis:6.2-alpine
    container_name: tls-redis-replica2
    network_mode: host
    volumes:
      - ./replica2.conf:/etc/redis.conf:z
      - ./circleci.crt:/etc/redis.crt:z
      - ./circleci.key:/etc/redis.key:z
      - ./ca-circleci-cert.pem:/etc/ca-root-cert.pem:z
    command: [ redis-server, /etc/redis.conf, --slaveof, localhost, "46380" ]

  tls-redis-sentinel1:
    image: redis:6.2-alpine
    container_name: tls-redis-sentinel1
    network_mode: host
    volumes:
      - ./sentinel1_tls:/data:Z
      - ./circleci.crt:/etc/redis.crt:z
      - ./circleci.key:/etc/redis.key:z
      - ./ca-circleci-cert.pem:/etc/ca-root-cert.pem:z
    command: [ redis-server, /data/sentinel.conf, --sentinel ]

  tls-redis-sentinel2:
    image: redis:6.2-alpine
    container_name: tls-redis-sentinel2
    network_mode: host
    volumes:
      - ./sentinel2_tls:/data:Z
      - ./circleci.crt:/etc/redis.crt:z
      - ./circleci.key:/etc/redis.key:z
      - ./ca-circleci-cert.pem:/etc/ca-root-cert.pem:z
    command: [ redis-server, /data/sentinel.conf, --sentinel ]

  tls-redis-sentinel3:
    image: redis:6.2-alpine
    container_name: tls-redis-sentinel3
    network_mode: host
    volumes:
      - ./sentinel3_tls:/data:Z
      - ./circleci.crt:/etc/redis.crt:z
      - ./circleci.key:/etc/redis.key:z
      - ./ca-circleci-cert.pem:/etc/ca-root-cert.pem:z
    command: [ redis-server, /data/sentinel.conf, --sentinel ]

  twemproxy:
    image: quay.io/3scale/twemproxy:v0.5.0
    container_name: twemproxy
    network_mode: host
    environment:
      - TWEMPROXY_CONFIG_FILE=/etc/twemproxy/nutcracker.yml
    volumes:
      - ./twemproxy.yml:/etc/twemproxy/nutcracker.yml:Z

  redis-shard1:
    image: redis:6.2-alpine
    container_name: redis-shard1
    network_mode: host
    command: [ redis-server, --port, "6382" ]

  redis-shard2:
    image: redis:6.2-alpine
    container_name: redis-shard2
    network_mode: host
    command: [ redis-server, --port, "6383" ]

  redis-shard3:
    image: redis:6.2-alpine
    container_name: redis-shard3
    network_mode: host
    command: [ redis-server, --port, "6384" ]
